package lyons.common.mapper.goods;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import lyons.common.model.goods.Goods;

public interface GoodsMapper {
    
    List<Goods> selectAll();

    List<Goods> selectByCondition(@Param("keyword") String keyword);

    Goods selectBygId(int gId);

    
    
    
    
    
/*    
    
    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Mon Feb 06 18:29:33 CST 2017
     *//*
    int countByExample(GoodsExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Mon Feb 06 18:29:33 CST 2017
     *//*
    int deleteByExample(GoodsExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Mon Feb 06 18:29:33 CST 2017
     *//*
    int insert(Goods record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Mon Feb 06 18:29:33 CST 2017
     *//*
    int insertSelective(Goods record);


    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Mon Feb 06 18:29:33 CST 2017
     *//*
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Mon Feb 06 18:29:33 CST 2017
     *//*
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);
*/}